### PR TITLE
Midproject

### PR DESCRIPTION
**Pull request by shiva-msia**
**Configuration Files:**

- DB Config file for mySQL configuration: [config/db_config.yml ](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/config/dbconfig.yml)
- requirements.txt [/requirements.txt](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/requirements.txt)

**Python scripts:**

- Script to write PUBG data (csv) into your local working directory: [src/write_to_local.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/write_to_local.py)
- Script to write PUBG data (csv) into your s3: [src/write_to_s3.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/write_to_s3.py)
- Script to create database in SQLite: [src/create_database_sqlite.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/create_database_sqlite.py)
- Script to create functions to create database in RDS: [src/create_database_rds.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/create_database_rds.py)
- Script to run create_database_rds: [src/run_create_database_rds.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/run_create_database_rds.py)
- Script containing configuration for other src files: [src/config.py](https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction/blob/master/src/config.py)

**Steps to create a new conda environment to run python scripts:**
1. SSH onto remote
   > ssh <net-id<net-id>>@msia423.analytics.northwestern.edu
2. Create new environment
  > conda create --name pubg python=3.7
  > conda activate pubg
3. Clone the git project into the env:  pubg
  > git init
  > git clone https://github.com/shiva-msia/PUBG-Finish-Placement-Prediction.git
4. Go into PUBG-Finish-Placement-Prediction folder
  > cd PUBG-Finish-Placement-Prediction/
5. Install requirements.txt file
  > pip install -r requirements.txt
6. go into src folder
  > cd src/
7. configure AWS settings with your username and pass credentials
  > aws configure
      > enter your secret key id
      > and secret key password
      > pros enter for default region name
      > press enter for default output format

**Running python scripts**

**write_to_local.py** - Write PUBG train.csv and test.csv into local working directory
Command to run: **python write_to_local.py**

**write_to_s3.py** - Write PUBG train.csv and test.csv into desired s3 folder
Command to run: 
**1. vi  write_to_s3.py and update the AWS bucket name(in the last line of the code) to desired AWS S3 bucket to which data need to be transferred 
   2. python write_to_s3.py**
--make sure to update the S3 bucket name to desired bucket name in src/write_to_s3.py

**create_database_sqlite.py** -Create PUBG database in SQLlite
Command to run: **python create_database_sqlite.py**
--the database will be created in the current working directory

**run_create_database_rds.py** -Create PUBG database in RDS
Command to run: 
**1. cd ../config
   2. vi  db_config.yml and update the host to desired AWS RDS instance name
   3. cd ../src
   4. python run_create_database_rds.py --user <user<user>> --password <password<password>>**
--make sure to to enter user and password as arguments when running this script

To validate the database was created:
> cd ../data (to see the .db file created)
> sqlite3 pubg.db
> .schema train
> .schema test

### CODE REVIEW

**Comment by yayitsnaomi** [comment]
-Please add steps to configure s3 bucket and edit -Please add a note to update config file with my RDS host name

**Comment by yayitsnaomi** [comment]
-Overall the steps are neat and easy to follow by copy/pasting the links in the pull request into the terminal to execute
-Please note that user needs to  cd src to run the python scripts
-Please add steps for user to configure s3 bucket and note where in the file we need to update as there are several places
-Please add a note for user to update config file with my RDS host name. Steps:
cd ..  
cd config 
vi dbconfig.yml -> update host name to rds

**Comment by yayitsnaomi** [comment]
- Overall all the files submitted have clean, concise code that's easy to follow and understand. There are doc strings at the top of each file as well as within almost every function.
- Can add doc string for functions ifin & create_connection & in src/create_database_rds.py

**Comment by shiva-msia** [comment]
Updated the instructions to make the steps to seamlessly update S3 and RDS configurations

**Pull request merged**
